// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID          int64              `db:"id" json:"id"`
	UserID      *int64             `db:"user_id" json:"user_id"`
	OrderDate   pgtype.Timestamptz `db:"order_date" json:"order_date"`
	TotalAmount int64              `db:"total_amount" json:"total_amount"`
}

type Orderproduct struct {
	OrderID   *int64 `db:"order_id" json:"order_id"`
	ProductID *int64 `db:"product_id" json:"product_id"`
}

type Product struct {
	ID    int64  `db:"id" json:"id"`
	Name  string `db:"name" json:"name"`
	Price int64  `db:"price" json:"price"`
}

type User struct {
	ID       int64  `db:"id" json:"id"`
	Name     string `db:"name" json:"name"`
	Email    string `db:"email" json:"email"`
	Password string `db:"password" json:"password"`
}
