// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"
)

type Querier interface {
	GetOrdersByUserId(ctx context.Context, id int64) ([]*Order, error)
	GetUserStatistics(ctx context.Context) ([]*GetUserStatisticsRow, error)
	GetUsersAndProducts(ctx context.Context, arg GetUsersAndProductsParams) ([]*GetUsersAndProductsRow, error)
}

var _ Querier = (*Queries)(nil)
