// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateOrder = `-- name: CreateOrder :one
INSERT INTO Orders (user_id, order_date, total_amount)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateOrderParams struct {
	UserID      *int64             `db:"user_id" json:"user_id"`
	OrderDate   pgtype.Timestamptz `db:"order_date" json:"order_date"`
	TotalAmount int64              `db:"total_amount" json:"total_amount"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, CreateOrder, arg.UserID, arg.OrderDate, arg.TotalAmount)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const CreateOrderProduct = `-- name: CreateOrderProduct :one
INSERT INTO orderproducts (order_id, product_id)
VALUES ($1, $2)
RETURNING order_id
`

type CreateOrderProductParams struct {
	OrderID   *int64 `db:"order_id" json:"order_id"`
	ProductID *int64 `db:"product_id" json:"product_id"`
}

func (q *Queries) CreateOrderProduct(ctx context.Context, arg CreateOrderProductParams) (*int64, error) {
	row := q.db.QueryRow(ctx, CreateOrderProduct, arg.OrderID, arg.ProductID)
	var order_id *int64
	err := row.Scan(&order_id)
	return order_id, err
}

const CreateProduct = `-- name: CreateProduct :one
INSERT INTO Products (name, price)
VALUES ($1, $2)
RETURNING id
`

type CreateProductParams struct {
	Name  string `db:"name" json:"name"`
	Price int64  `db:"price" json:"price"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (int64, error) {
	row := q.db.QueryRow(ctx, CreateProduct, arg.Name, arg.Price)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const CreateUser = `-- name: CreateUser :one
INSERT INTO Users (name, email, password)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateUserParams struct {
	Name     string `db:"name" json:"name"`
	Email    string `db:"email" json:"email"`
	Password string `db:"password" json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, CreateUser, arg.Name, arg.Email, arg.Password)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const DeleteOrder = `-- name: DeleteOrder :one
DELETE
FROM Orders
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteOrder(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, DeleteOrder, id)
	err := row.Scan(&id)
	return id, err
}

const DeleteProduct = `-- name: DeleteProduct :one
DELETE
FROM Products
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, DeleteProduct, id)
	err := row.Scan(&id)
	return id, err
}

const DeleteUser = `-- name: DeleteUser :one
DELETE
FROM Users
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, DeleteUser, id)
	err := row.Scan(&id)
	return id, err
}

const GetOrderById = `-- name: GetOrderById :one
SELECT DISTINCT o.id, o.user_id, o.order_date, o.total_amount
FROM Orders o
WHERE o.id = $1
`

func (q *Queries) GetOrderById(ctx context.Context, id int64) (*Order, error) {
	row := q.db.QueryRow(ctx, GetOrderById, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderDate,
		&i.TotalAmount,
	)
	return &i, err
}

const GetOrders = `-- name: GetOrders :many
SELECT o.id, o.user_id, o.order_date, o.total_amount
FROM Orders o
ORDER BY o.id
LIMIT $1 OFFSET $2
`

type GetOrdersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) GetOrders(ctx context.Context, arg GetOrdersParams) ([]*Order, error) {
	rows, err := q.db.Query(ctx, GetOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrderDate,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetOrdersByUserId = `-- name: GetOrdersByUserId :many
SELECT o.id, o.user_id, o.order_date, o.total_amount
FROM Orders o
         JOIN Users u ON o.user_id = u.id
WHERE u.id = $1
`

func (q *Queries) GetOrdersByUserId(ctx context.Context, id int64) ([]*Order, error) {
	rows, err := q.db.Query(ctx, GetOrdersByUserId, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrderDate,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetProductById = `-- name: GetProductById :one
SELECT DISTINCT p.id, p.name, p.price
FROM Products p
WHERE p.id = $1
`

func (q *Queries) GetProductById(ctx context.Context, id int64) (*Product, error) {
	row := q.db.QueryRow(ctx, GetProductById, id)
	var i Product
	err := row.Scan(&i.ID, &i.Name, &i.Price)
	return &i, err
}

const GetProducts = `-- name: GetProducts :many
SELECT p.id, p.name, p.price
FROM Products p
ORDER BY p.id
LIMIT $1 OFFSET $2
`

type GetProductsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) GetProducts(ctx context.Context, arg GetProductsParams) ([]*Product, error) {
	rows, err := q.db.Query(ctx, GetProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(&i.ID, &i.Name, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserById = `-- name: GetUserById :one
SELECT DISTINCT u.id, u.name, u.email, u.password
FROM Users u
WHERE u.id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (*User, error) {
	row := q.db.QueryRow(ctx, GetUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
	)
	return &i, err
}

const GetUserStatistics = `-- name: GetUserStatistics :many
SELECT u.name,
       COUNT(o)                                       AS orderNumber,
       SUM(o.total_amount)                            AS orderTotalSum,
       to_char(AVG(o.total_amount), 'FM999999999.00') AS avgSum
FROM Users u
         JOIN Orders o ON o.user_id = u.id
GROUP BY u.name
`

type GetUserStatisticsRow struct {
	Name          string `db:"name" json:"name"`
	Ordernumber   int64  `db:"ordernumber" json:"ordernumber"`
	Ordertotalsum int64  `db:"ordertotalsum" json:"ordertotalsum"`
	Avgsum        string `db:"avgsum" json:"avgsum"`
}

func (q *Queries) GetUserStatistics(ctx context.Context) ([]*GetUserStatisticsRow, error) {
	rows, err := q.db.Query(ctx, GetUserStatistics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetUserStatisticsRow{}
	for rows.Next() {
		var i GetUserStatisticsRow
		if err := rows.Scan(
			&i.Name,
			&i.Ordernumber,
			&i.Ordertotalsum,
			&i.Avgsum,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUsers = `-- name: GetUsers :many
SELECT u.id, u.name, u.email, u.password
FROM Users u
ORDER BY u.id
LIMIT $1 OFFSET $2
`

type GetUsersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, GetUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUsersAndProducts = `-- name: GetUsersAndProducts :many
SELECT o.id   AS orderId,
       u.name AS userName,
       p.name AS productName,
       p.price
FROM Users u
         JOIN Orders o ON o.user_id = u.id
         JOIN OrderProducts op ON op.order_id = o.id
         JOIN Products p ON p.id = op.product_id
ORDER BY o.id
LIMIT $1 OFFSET $2
`

type GetUsersAndProductsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetUsersAndProductsRow struct {
	Orderid     int64  `db:"orderid" json:"orderid"`
	Username    string `db:"username" json:"username"`
	Productname string `db:"productname" json:"productname"`
	Price       int64  `db:"price" json:"price"`
}

func (q *Queries) GetUsersAndProducts(ctx context.Context, arg GetUsersAndProductsParams) ([]*GetUsersAndProductsRow, error) {
	rows, err := q.db.Query(ctx, GetUsersAndProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetUsersAndProductsRow{}
	for rows.Next() {
		var i GetUsersAndProductsRow
		if err := rows.Scan(
			&i.Orderid,
			&i.Username,
			&i.Productname,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateOrder = `-- name: UpdateOrder :one
UPDATE Orders
SET user_id      = $1,
    order_date   = $2,
    total_amount = $3
WHERE id = $4
RETURNING id
`

type UpdateOrderParams struct {
	UserID      *int64             `db:"user_id" json:"user_id"`
	OrderDate   pgtype.Timestamptz `db:"order_date" json:"order_date"`
	TotalAmount int64              `db:"total_amount" json:"total_amount"`
	ID          int64              `db:"id" json:"id"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, UpdateOrder,
		arg.UserID,
		arg.OrderDate,
		arg.TotalAmount,
		arg.ID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const UpdateProduct = `-- name: UpdateProduct :one
UPDATE Products
SET name  = $1,
    price = $2
WHERE id = $3
RETURNING id
`

type UpdateProductParams struct {
	Name  string `db:"name" json:"name"`
	Price int64  `db:"price" json:"price"`
	ID    int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (int64, error) {
	row := q.db.QueryRow(ctx, UpdateProduct, arg.Name, arg.Price, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const UpdateUser = `-- name: UpdateUser :one
UPDATE Users
SET name     = $1,
    email    = $2,
    password = $3
WHERE id = $4
RETURNING id
`

type UpdateUserParams struct {
	Name     string `db:"name" json:"name"`
	Email    string `db:"email" json:"email"`
	Password string `db:"password" json:"password"`
	ID       int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, UpdateUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.ID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
